=== WSN-2012/BPF/config/dtn.config.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.bytewalla.tslab.ssvl.kth.se/DTNConf" elementFormDefault="qualified" targetNamespace="http://www.bytewalla.tslab.ssvl.kth.se/DTNConf">


    <complexType name="DTNConfiguration">
    	<all>
    		<element name="StorageSetting" type="tns:StorageSetting"/>
    		<element name="InterfacesSetting" type="tns:InterfacesSetting">
    		</element>
    		<element name="LinksSetting" type="tns:LinksSetting"/>
    		<element name="RoutesSetting" type="tns:RoutesSetting"/>
    		<element name="DiscoveriesSetting" type="tns:DiscoveriesSetting"/>
    	</all>
    </complexType>

    <element name="DTNConfiguration" type="tns:DTNConfiguration"/>


    <complexType name="StorageSetting">
    	<attribute name="quota" type="int">
    		<annotation>
    			<documentation>
    				Storage Quota setting (MB)
    			</documentation>
    		</annotation>
    	</attribute>
    	<attribute name="storage_path" type="string" use="required"/>
    </complexType>

    <complexType name="Interface">
    	<attribute name="id" type="string" use="required"/>
    	<attribute name="local_port" type="int" use="optional"/>
    	<attribute name="conv_layer_type">
    	
    		<simpleType>
    			<restriction base="string">
    				<enumeration value="tcp"/>
    			</restriction>
    		</simpleType>
    	</attribute>
    </complexType>



    <complexType name="InterfacesSetting">
    	<sequence>
    		<element maxOccurs="unbounded" minOccurs="0" name="Interface" type="tns:Interface">
    		</element>
    	</sequence>
    </complexType>

    <complexType name="Link">
    	<attribute name="id" type="string" use="required"/>
    	<attribute name="dest" type="string"/>
    	<attribute name="type">
    		<simpleType>
    			<restriction base="string">
    				<enumeration value="ALWAYSON"/>
    				<enumeration value="ONDEMAND"/>
    				<enumeration value="SCHEDULED"/>
    				<enumeration value="OPPORTUNISTIC"/>
    			</restriction>
    		</simpleType>
    	</attribute>
    	<attribute name="conv_layer_type">
    		<simpleType>
    			<restriction base="string">
    				<enumeration value="tcp"/>
    			</restriction>
    		</simpleType>
    	</attribute>
    </complexType>

    <complexType name="LinksSetting">
    	<sequence>
    		<element maxOccurs="unbounded" minOccurs="0" name="Link" type="tns:Link"/>
    	</sequence>
    </complexType>

    <complexType name="Route">
    	<attribute name="dest" type="string" use="required"/>
    	<attribute name="link_id" type="string"/>
    </complexType>
    
    <complexType name="RoutesSetting">
    	<sequence>
    		<element maxOccurs="unbounded" minOccurs="0" name="Route" type="tns:Route">
    		</element>
    	</sequence>
    	<attribute name="router_type" use="required">
    		<simpleType>
    			<restriction base="string">
    				<enumeration value="static"/>
    				<enumeration value="prophet"/>
    			</restriction>
    		</simpleType>
    	</attribute>
    	<attribute name="local_eid" type="string"/>
    	
	    	<attribute name="P_encounter" type="float"/>
    		<attribute name="P_encounter_first" type="float"/>
    		
    		<attribute name="alpha" type="float"/>
    		<attribute name="beta" type="float"/>
    		<attribute name="delta" type="float"/>
    		<attribute name="K" type="int"/>
    		<attribute name="queuing" type="string"/>
 	
    </complexType>
    

    <complexType name="Discovery">
    	<attribute name="id" type="string" use="required"/>
    	<attribute name="address_family">
    		<simpleType>
    			<restriction base="string">
    				<enumeration value="ip"/>
    			</restriction>
    		</simpleType>
    	</attribute>
    	<attribute name="port" type="int"/>
    </complexType>

    <complexType name="DiscoveriesSetting">
    	<sequence>
    		<element maxOccurs="unbounded" minOccurs="0" name="Discovery" type="tns:Discovery"/>
    		<element maxOccurs="unbounded" minOccurs="0" name="Announce" type="tns:Announce"/>
    	</sequence>
    </complexType>

    <complexType name="Announce">
    	<attribute name="interface_id" type="string" use="required"/>
    	<attribute name="discovery_id" type="string"/>
    	<attribute name="conv_layer_type" type="string"/>
    	<attribute name="interval" type="int" use="optional"/>
    </complexType>
</schema>

=== WSN-2012/BPF/config/sample-dtn.config.xml/emulator.dtn.config.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--  Main configuration file for Android DTN Project -->
<tns:DTNConfiguration xmlns:tns="http://www.bytewalla.tslab.ssvl.kth.se/DTNConf" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.bytewalla.tslab.ssvl.kth.se/DTNConf dtn.config.xsd">
			
	<!--  Storage Section -->
	<!--  Setup your storage here -->
	<!--  type can be phone or sdcard -->
	<!--  quota is the space you will allow DTN to store bundles
	  in the storage type you set, the unit is Megabytes -->
	<tns:StorageSetting type="sdcard" quota="50" storage_path="dtn"/>
	
	
	<!--  Interfaces Section -->
	<tns:InterfacesSetting>
	<!--  Setup your listening interfaces here -->
	   <tns:Interface id="tcp0" conv_layer_type="tcp"  local_port="7000"/>
	</tns:InterfacesSetting>
	
	
	<!--  Links Section -->
	<tns:LinksSetting>
	<!--  Setup your links here -->
		<tns:Link id="village_tcp_link" conv_layer_type="tcp" dest="10.0.2.2:9000" type="ONDEMAND" />
		<tns:Link id="city_tcp_link"    conv_layer_type="tcp" dest="10.0.2.2:9001" type="ONDEMAND" />
		
	</tns:LinksSetting>
	
	
	<!--  Routes Section -->
	<tns:RoutesSetting router_type="static" local_eid="dtn://rerngvit.bytewalla.com">
	<!--  Setup your routes here -->
		<tns:Route dest="dtn://village.bytewalla.com/*" link_id="village_tcp_link"/>
		<tns:Route dest="dtn://city.bytewalla.com/*" link_id="city_tcp_link"/>
	</tns:RoutesSetting>
	
	
	<tns:DiscoveriesSetting>
	<!--  Setup your Discovery here -->
	</tns:DiscoveriesSetting>
	
</tns:DTNConfiguration>

=== WSN-2012/BPF/test/se/kth/ssvl/tslab/wsn/general/servlib/config/dtn.config.xml
<?xml version="1.0" encoding="UTF-8"?>

    <!--  Main configuration file for Android DTN Project -->
    <!--  Its XML Schema is dtn.config.xsd in the same folder -->
<tns:DTNConfiguration xmlns:tns="http://www.bytewalla.tslab.ssvl.kth.se/DTNConf"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.bytewalla.tslab.ssvl.kth.se/DTNConf dtn.config.xsd">

    <!--  Storage Section -->
    <!--  Setup your storage here -->
    <!--
        quota is the space you will allow DTN to store bundles in the storage
        type you set, the unit is Megabytes
    -->
    <tns:StorageSetting quota="1" storage_path="test/se/kth/ssvl/tslab/wsn/general/servlib/config/build/dtn" test_data_log="true"/>


    <!--  Interfaces Section -->
    <tns:InterfacesSetting>
        <!--  Setup your listening interfaces here -->
        <tns:Interface id="tcp0" conv_layer_type="tcp"
            local_port="4556" />
    </tns:InterfacesSetting>


    <!--  Links Section -->
    <tns:LinksSetting proactive_fragmentation="true" fragmentation_mtu="5000">
        <!--  Setup your links here -->
        <tns:Link id="bifrost_tcp_link" conv_layer_type="tcp" dest="192.168.0.1:4556" type="ONDEMAND" />
    </tns:LinksSetting>


    <!--  Routes Section -->
    <tns:RoutesSetting local_eid="dtn://linux.dtn" router_type="prophet" P_encounter="0.5"
        P_encounter_first="0.25" delta="0.01" alpha="0.5" beta="0.9" K="1" queuing="Fifo">
        <!--  Setup your routes here -->
        <tns:Route dest="dtn://city.bytewalla.com/*" link_id="bifrost_tcp_link"/>
        <tns:Route dest="dtn://village.bytewalla.com/*" link_id="bifrost_tcp_link"/>
        <tns:Route dest="dtn://bifrost.bytewalla.com/*" link_id="bifrost_tcp_link"/>
    </tns:RoutesSetting>

    <tns:DiscoveriesSetting>
        <!--  Setup your Discovery here -->
        <tns:Discovery id="ipdisc0" address_family="ip" port="9556"></tns:Discovery>
        <tns:Announce interface_id="tcp0" discovery_id="ipdisc0"
            conv_layer_type="tcp"></tns:Announce>
    </tns:DiscoveriesSetting>
    
    <!-- Security Settings -->
    <!-- ks_path: the path to the keystore -->
    <!-- ks_password: password to access the keystore -->
    <!-- use_pcb [true|false]: Payload Confidentiality Block for confidentiality and integrity -->
    <!-- use_pib [true|false]: Payload Integrity Block for integrity and authenticity -->
    <tns:SecuritySetting ks_path="path/to/keystore" ks_password="password" use_pcb="true" use_pib="false"></tns:SecuritySetting>

</tns:DTNConfiguration>

=== WSN-2012/BPF/config/sample-dtn.config.xml/flood.dtn.config.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--  Main configuration file for Android DTN Project -->
<tns:DTNConfiguration xmlns:tns="http://www.bytewalla.tslab.ssvl.kth.se/DTNConf" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.bytewalla.tslab.ssvl.kth.se/DTNConf dtn.config.xsd">
			
	<!--  Storage Section -->
	<!--  Setup your storage here -->
	<!--  type can be phone or sdcard -->
	<!--  quota is the space you will allow DTN to store bundles
	  in the storage type you set, the unit is Megabytes -->
	<tns:StorageSetting type="sdcard" quota="50" storage_path="dtn"/>
	
	
	<!--  Interfaces Section -->
	<tns:InterfacesSetting>
	<!--  Setup your listening interfaces here -->
	   <tns:Interface id="tcp0" conv_layer_type="tcp" local_port="4556"/>
	</tns:InterfacesSetting>
	
	
	<!--  Links Section -->
	<tns:LinksSetting>
	<!--  Setup your links here -->
	</tns:LinksSetting>
	
	
	<!--  Routes Section -->
	<tns:RoutesSetting router_type="flood" local_eid="dtn://android.dtn">
	<!--  Setup your routes here -->
	</tns:RoutesSetting>
	
	
	<tns:DiscoveriesSetting>
	<!--  Setup your Discovery here --> 
		<tns:Discovery address_family="ip" id="discovery1" port="2000"/>
	    <tns:Announce  interface_id="tcp0" discovery_id="discovery1"  conv_layer_type="tcp" interval="5"/>
	
	</tns:DiscoveriesSetting>
	
</tns:DTNConfiguration>
